# Generated by Django 3.1.7 on 2021-04-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='название')),
                ('description', models.CharField(max_length=150, verbose_name='описание')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('photo', models.FileField(upload_to='src/photos', verbose_name='фото')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
    ]
