# Generated by Django 3.1.7 on 2021-05-13 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0003_bookingroommodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingroommodel',
            name='person_name',
        ),
        migrations.AddField(
            model_name='bookingroommodel',
            name='name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingroommodel',
            name='names',
            field=models.CharField(default='lalala', max_length=10),
        ),
    ]
