# Generated by Django 3.1.7 on 2021-05-13 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0004_auto_20210513_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingroommodel',
            name='name',
            field=models.ForeignKey(default='s', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
