# Generated by Django 3.1.7 on 2021-05-17 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20210513_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingroommodel',
            name='names',
        ),
    ]
