# Generated by Django 3.1.7 on 2021-05-17 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_remove_bookingroommodel_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingroommodel',
            name='room_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rooms.roommodel'),
        ),
    ]
