# Generated by Django 3.1.7 on 2021-04-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardRentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('photo', models.ImageField(upload_to='images', verbose_name='фото')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('description', models.CharField(max_length=200, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'сноуборд',
                'verbose_name_plural': 'сноуборды',
            },
        ),
        migrations.CreateModel(
            name='SkiRentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('photo', models.ImageField(upload_to='images', verbose_name='фото')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('description', models.CharField(max_length=200, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'лыжи',
                'verbose_name_plural': 'лыжи',
            },
        ),
    ]
