# Generated by Django 3.1.7 on 2021-04-28 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ski_resort', '0003_auto_20210428_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choices',
            options={'verbose_name': 'размер', 'verbose_name_plural': 'размеры'},
        ),
    ]
