# Generated by Django 3.1.7 on 2021-05-19 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ski_resort', '0005_auto_20210428_1632'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoardRentModel',
        ),
        migrations.RemoveField(
            model_name='bootsrentmodel',
            name='size',
        ),
        migrations.DeleteModel(
            name='SkiRentModel',
        ),
        migrations.DeleteModel(
            name='BootsRentModel',
        ),
        migrations.DeleteModel(
            name='Choices',
        ),
    ]
